<?php $products = $this->getProductCollection(); ?>
<?php if($products == null) return ?>

<?php if($products->count() > 0): ?>
<div id="last-reviewed-products" class="block last-reviewed">
    <div class="block-title">
        <strong><span><?php echo $this->__("Last Reviewed"); ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="reviewed-list">
            <?php foreach($products as $product): ?>
            <?php
                $review = Mage::helper('customwidgets')->getLastProductReview($product->getId());
                $avg = 0;
                $ratings = array();
                if(count($review) > 0) {
                        foreach($review->getRatingVotes() as $_vote):
                            $ratings[] = $_vote->getPercent();
                        endforeach;
                    if(count($ratings) > 0) {
                        $avg = array_sum($ratings)/count($ratings);
                    } else {
                        $avg = array_sum($ratings)/1;
                    }
                }
            ?>
                <li class="product">
                    <div class="top">
                        <div class="image">
                            <a href="<?php echo Mage::getBaseUrl().$product->getUrlPath() ?>" title="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" class="product-image">
                            <?php 
                                $_imgWidth =  $this->getImageWidth();
                                $_imgHeight =  $this->getImageHeight(); 
                            ?>
                            <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize($_imgWidth, $_imgHeight); ?>"
                                 width="<?php echo $_imgWidth; ?>" height="<?php echo $_imgHeight; ?>"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" />
                            </a>
                        </div>
                        <div class="info">
                            <div class="manufacturer"><?php echo $product->getAttributeText('manufacturer'); ?></div>
                            <div class="product-name"><a href="<?php echo $product->getProductUrl() ?>"><?php echo Mage::helper('catalog/output')->productAttribute($product, $product->getName(), 'name') ?></a></div>
                            <?php if($avg > 0): ?>
                                <div class="ratings">
                                    <div class="rating-box">
                                        <div class="rating" style="width:<?php echo ceil($avg); ?>%;">
                                        </div>
                                    </div>
                                </div>
                                <span class="rating-value">(
                                <?php
                                    $value = (float) round($avg/20, 1, PHP_ROUND_HALF_EVEN);
                                    echo sprintf('%.1f',$value);
                                ?> )</span>

                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="review">
                        <div class="title"><?php echo $review->getTitle(); ?></div>
                        <div class="desc"><?php echo $review->getDetail(); ?></div>
                    </div>
                </li>
            <?php endforeach;  ?>
        </ul>
    </div>
</div>
<?php endif; ?>
